### ISSUE TITLE
Would you consider getting this in Debian repositories?

### ISSUE THREAD

**Issue by brandonros** [hartkopp/can-isotp#17]

**Comment by hartkopp** [comment]
Hm - no.
I consider to bring this upstream. After the presentation of CAN_J1939 at Embedded Linux Conference Europe last month, I feel confident to send this on the mailing list too :-)

**Comment by brandonros** [comment]
ah yes, that is the better option.

I think it will land nicely, it is very good work. Thank you for all of your efforts!!!

**Comment by hartkopp** [comment]
Are you subscribed to the linux-can mailing list?
If you are interested in testing the upstream version it would be cool to stay in touch there.
Are you using the master branch of can-isotp or e.g. the softhrt branch (https://github.com/hartkopp/can-isotp/commits/softhrt) I tend to post for mainline inclusion?
