### ISSUE TITLE
What *should* isotpdump look like?

### ISSUE THREAD

**Issue by granmadave** [hartkopp/can-isotp#19]
isotpdump doesn't look right; do you have any screenshots of examples showing what the -s and -d (and results) should look like?

**Comment by hartkopp** [comment]
isotpdump uses the CAN_RAW socket and interprets the received PDU CAN frames without knowing about the iso-tp protocol itself.

An example can be found here on slide 31:
https://wiki.automotivelinux.org/_media/agl-distro/agl2017-socketcan-print.pdf

**Comment by hartkopp** [comment]
Hi @granmadave 
Can this issue be closed?
