### ISSUE TITLE
Canfd support on virtual can?

### ISSUE THREAD

**Issue by swanandb2** [hartkopp/can-isotp#29]
I want to learn can fd unfortunately I have pi can2 bord which does not support can fd. I am wondering if I can use virtual can for canfd?

**Comment by hartkopp** [comment]
Yes, you can use the virtual CAN for CAN FD and ISO-TP.
By default vcan devices are created as CAN FD devices which you can see from the **MTU** value (CAN = 16, CAN FD = **72**):

`$ ip -det link show vcan0

4: vcan0: <NOARP,UP,LOWER_UP> mtu 72 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/can  promiscuity 0 minmtu 0 maxmtu 0 
    vcan numtxqueues 1 numrxqueues 1 gso_max_size 65536 gso_max_segs 65535 
`
