### ISSUE TITLE
no license specified

### ISSUE THREAD

**Issue by gizero** [hartkopp/can-isotp#4]
Hi!
I'm working on including your kernel module into an embedded distribution build framework (OpenEmbedded). I noticed there is no reference to the license this code is available under. I'd expect it to be GPLv2, but having it clearly stated would be much appreciated. If that's the case, could you please add the GPLv2 `COPYING` file to the repo?

**Comment by hartkopp** [comment]
Hi Andrea. Added COPYING file to document the code license.
Thanks for your suggestion!
