### ISSUE TITLE
Not able to build for raspberry pi

### ISSUE THREAD

**Issue by Kallappambk** [hartkopp/can-isotp#45]
Hello ,

i am trying to build the ISO TP for the R-PI, But i am getting the error like below when I am executing the command :
sudo apt-get install build-essential linux-headers-$(uname -r)

kindly help me with this I am really new to this.

**pi@raspberrypi:~/can-isotp $ sudo apt-get install build-essential linux-headers-$(uname -r)
Reading package lists... Done
Building dependency tree      
Reading state information... Done
E: Unable to locate package linux-headers-5.10.17-v7l
E: Couldn't find any package by glob 'linux-headers-5.10.17-v7l'
E: Couldn't find any package by regex 'linux-headers-5.10.17-v7l'** 

Hardware Details :
R-PI 4 .
OS :  rasbian deb_buster version

Regards,
Kallappa

**Comment by hartkopp** [comment]
Hi Kallappa,

let me google this for you :-D

https://www.google.de/search?q=+Unable+to+locate+package+linux-headers-5.10.17-v7l

https://www.raspberrypi.org/forums/viewtopic.php?t=210821

https://www.raspberrypi.org/forums/viewtopic.php?t=210821#p1302421

Can you try that?

Thanks,
Oliver
