### ISSUE TITLE
difference between python-can-isotp and can-isotp and stmin discrepancy 

### ISSUE THREAD

**Issue by Yodawgz0** [hartkopp/can-isotp#46]
While going through a solution for stmin discrepancy like it was not consistent with stmin timings , I came across yours and pylessard's python-can-istotp.
please can you highlight implementation  and what would be the best solution in order to use flow control for multiframe which is having stmin.

**Comment by pylessard** [comment]
@Yodawgz0 ,  my module make usage of @hartkopp's module. Mine is just a Python wrapper over his work.

![image](https://user-images.githubusercontent.com/2386969/124273061-8bb6c180-db0d-11eb-9a3d-136d9fda9ef2.png)

**Comment by Yodawgz0** [comment]
Thank you for clearing that out :)
