### ISSUE TITLE
how to send > 4095 isotp message

### ISSUE THREAD

**Issue by jinbaotang** [hartkopp/can-isotp#50]

**Comment by jinbaotang** [comment]
![image](https://user-images.githubusercontent.com/49639435/146704608-e3e7ac4d-b932-4775-ad28-4897d1ea5aa1.png)
I want to use cantp data length > 4095, but I read the isotp.h, cannot find the optional to set?is isotp support it?

**Comment by hartkopp** [comment]
Hi,
to be able to test this feature I set the max. PDU length to 8200, see here:
https://github.com/hartkopp/can-isotp/blob/master/net/can/isotp.c#L110
https://github.com/torvalds/linux/blob/master/net/can/isotp.c#L86

I have no final idea what needs to be done, when users *really* want to transfer 4Gbyte PDUs - but even with the current implementation you can transfer e.g. 8000 byte PDUs which should automatically switch to the FF_DL representation depicted in your request.

Please let me know when you run into problems with it. Thanks!

**Comment by jinbaotang** [comment]
> Hi, to be able to test this feature I set the max. PDU length to 8200, see here: https://github.com/hartkopp/can-isotp/blob/master/net/can/isotp.c#L110 https://github.com/torvalds/linux/blob/master/net/can/isotp.c#L86
> 
> I have no final idea what needs to be done, when users _really_ want to transfer 4Gbyte PDUs - but even with the current implementation you can transfer e.g. 8000 byte PDUs which should automatically switch to the FF_DL representation depicted in your request.
> 
> Please let me know when you run into problems with it. Thanks!

thank harkopp, I got it
