### ISSUE TITLE
MAX_MSG_LENGTH to 66000 commit is missing from this repo

### ISSUE THREAD

**Issue by derek-will** [hartkopp/can-isotp#53]
The commit that set MAX_MSG_LENGTH to 66000 is missing from this repo. Can this commit be added in?

For reference: https://elixir.bootlin.com/linux/v5.18-rc1/source/net/can/isotp.c#L91

**Comment by hartkopp** [comment]
Thanks for the heads up!

https://github.com/hartkopp/can-isotp/commit/270406fece110c1840c5048d3ec9e56053bca4d8
