### ISSUE TITLE
fatal error: linux/can/isotp.h: No such file or directory

### ISSUE THREAD

**Issue by akast** [hartkopp/can-isotp#6]
akast@ubuntu:~/can-isotp/net/can$ make
make -C /lib/modules/4.10.0-19-generic/build M=/home/akast/can-isotp/net/can modules
make[1]: Entering directory '/usr/src/linux-headers-4.10.0-19-generic'
  CC [M]  /home/akast/can-isotp/net/can/isotp.o
/home/akast/can-isotp/net/can/isotp.c:68:29: fatal error: linux/can/isotp.h: No such file or directory
 #include <linux/can/isotp.h>
                             ^
compilation terminated.

**Comment by hartkopp** [comment]
You need to be in 'can-isotp/' and not in 'can-isotp/net/can/' to run 'make'
Please just follow the README.

Oh - just seen that this documentation was missing.
Thanks for the hint!
