### ISSUE TITLE
Can't open utils' source code refence

### ISSUE THREAD

**Issue by Semant1ka** [hartkopp/can-isotp#8]
Hi,
Just wanted to check utils' source code on the [link](http://developer.berlios.de/svn/?group_id=6475) that you provided in howto, but I wasn't able to make my browser to resolve it.
Does this site still exist and up?

**Comment by hartkopp** [comment]
Thanks for the hint!!

Fixed in https://github.com/hartkopp/can-isotp/commit/a7dfaac19e3f6de039a5556f5ecdbbe3f6dc1454

Regards,
Oliver
